# Start from the official Ubuntu image
FROM ros:humble

# Install necessary packages
RUN apt-get update && \
    apt-get install -y \
        python3-pip \
        libgtk2.0-dev \
        pkg-config \
        libgl1-mesa-glx \
        libglib2.0-0 \
        libqt5x11extras5 \
        libx11-xcb1 \
        python3-pyaudio

RUN pip3 install \
        numpy  \
        opencv-python-headless  \
        flask \
        openai \
        requests \
        sounddevice \
        scipy

RUN pip3 install setuptools==58.2.0

WORKDIR /app
