# Start from the official Ubuntu image
FROM ros:humble

# Install necessary packages
RUN apt-get update && \
    apt-get install -y \
        python3-pip \
        python3-pyaudio

RUN pip3 install \
        numpy  \
        opencv-python-headless  \
        flask \
        openai \
        requests \
        sounddevice \
        scipy

RUN pip3 install setuptools==58.2.0

RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

WORKDIR /app
