FROM ros:humble

RUN apt-get update && \
    apt-get install -y \
        python3-pip

RUN pip3 install torch flask ultralytics

RUN pip3 install setuptools==58.2.0

RUN useradd -m -u 1000 -s /bin/bash user && \
    mkdir -p /app && \
    chown -R user:user /app

RUN usermod -aG video user

WORKDIR /app

USER user