FROM dustynv/ros:humble-pytorch-l4t-r32.7.1

RUN apt-get update && \
    apt-get install -y \
        libgtk2.0-dev \
        pkg-config \
        libgl1-mesa-glx \
        libglib2.0-0 \
        libqt5x11extras5 \
        libx11-xcb1 \
        v4l-utils

RUN pip3 install flask

RUN pip3 install setuptools==58.2.0

RUN useradd -m -u 1000 -s /bin/bash user && \
    mkdir -p /app && \
    chown -R user:user /app

RUN usermod -aG video user

WORKDIR /app

USER user